// 공항/도시 지식 DB — 항공권 검색 자동완성의 데이터 소스 (스카이스캐너·트립닷컴식 "아무 도시나 검색").
// 한국인이 실제로 검색하는 국제선 목적지를 지역별로 폭넓게 수록. Aviasales API가 전 노선을 커버하므로
// 여기 있는 도시는 인앱 가격 조회·트립닷컴 딥링크가 모두 동작한다.
// 형식: [IATA(도시/공항 코드), 한국어 이름, [별칭들(영문·이표기, 선택)]]
export const AIRPORT_REGIONS = [
  ['일본', [
    ['TYO', '도쿄', ['동경', 'tokyo', '하네다', '나리타']],
    ['KIX', '오사카', ['osaka', '간사이']],
    ['FUK', '후쿠오카', ['fukuoka']],
    ['CTS', '삿포로', ['홋카이도', 'sapporo']],
    ['OKA', '오키나와', ['okinawa']],
    ['NGO', '나고야', ['nagoya', '주부']],
    ['HIJ', '히로시마', ['hiroshima']],
    ['KOJ', '가고시마', ['kagoshima']],
    ['KMJ', '구마모토', ['kumamoto']],
    ['OIT', '오이타', ['oita', '벳푸']],
    ['NGS', '나가사키', ['nagasaki']],
    ['TAK', '다카마쓰', ['takamatsu']],
    ['MYJ', '마쓰야마', ['matsuyama']],
    ['SDJ', '센다이', ['sendai']],
    ['KMQ', '고마쓰', ['komatsu', '가나자와']],
    ['HKD', '하코다테', ['hakodate']],
    ['MMY', '미야코지마', ['miyako', '미야코']],
    ['ISG', '이시가키', ['ishigaki']],
  ]],
  ['대만 · 홍콩 · 마카오', [
    ['TPE', '타이베이', ['타이페이', '대북', 'taipei']],
    ['KHH', '가오슝', ['kaohsiung']],
    ['RMQ', '타이중', ['taichung']],
    ['HKG', '홍콩', ['hongkong']],
    ['MFM', '마카오', ['macau', 'macao']],
  ]],
  ['중국', [
    ['BJS', '베이징', ['북경', 'beijing', 'PEK']],
    ['SHA', '상하이', ['상해', 'shanghai', 'PVG']],
    ['TAO', '칭다오', ['청도', 'qingdao']],
    ['DLC', '다롄', ['대련', 'dalian']],
    ['CAN', '광저우', ['광주', 'guangzhou']],
    ['SZX', '선전', ['심천', 'shenzhen']],
    ['CTU', '청두', ['성도', 'chengdu']],
    ['XIY', '시안', ['서안', 'xian']],
    ['DYG', '장자제', ['장가계', 'zhangjiajie']],
    ['YNJ', '옌지', ['연길', 'yanji']],
    ['HRB', '하얼빈', ['harbin']],
    ['SYX', '싼야', ['삼아', 'sanya']],
    ['KMG', '쿤밍', ['곤명', 'kunming']],
    ['HGH', '항저우', ['항주', 'hangzhou']],
  ]],
  ['동남아', [
    ['DAD', '다낭', ['danang']],
    ['NHA', '나트랑', ['나짱', 'nhatrang']],
    ['PQC', '푸꾸옥', ['푸꾸억', '푸국', 'phuquoc']],
    ['HAN', '하노이', ['hanoi']],
    ['SGN', '호치민', ['사이공', 'hochiminh']],
    ['BKK', '방콕', ['bangkok']],
    ['HKT', '푸켓', ['phuket']],
    ['CNX', '치앙마이', ['chiangmai']],
    ['KBV', '끄라비', ['krabi']],
    ['CEB', '세부', ['cebu']],
    ['MNL', '마닐라', ['manila']],
    ['KLO', '보라카이', ['칼리보', 'boracay', 'kalibo']],
    ['CRK', '클락', ['clark', '앙헬레스']],
    ['BKI', '코타키나발루', ['코타', 'kk', 'kotakinabalu']],
    ['KUL', '쿠알라룸푸르', ['kualalumpur', '말레이시아']],
    ['PEN', '페낭', ['penang']],
    ['LGK', '랑카위', ['langkawi']],
    ['SIN', '싱가포르', ['singapore']],
    ['DPS', '발리', ['덴파사르', 'bali', 'denpasar']],
    ['CGK', '자카르타', ['jakarta']],
    ['REP', '시엠립', ['시엠리아프', 'siemreap', '앙코르와트']],
    ['PNH', '프놈펜', ['phnompenh']],
    ['VTE', '비엔티안', ['vientiane', '라오스']],
    ['LPQ', '루앙프라방', ['luangprabang']],
    ['RGN', '양곤', ['yangon', '미얀마']],
  ]],
  ['괌 · 사이판', [
    ['GUM', '괌', ['guam']],
    ['SPN', '사이판', ['saipan']],
  ]],
  ['미주', [
    ['NYC', '뉴욕', ['newyork', 'JFK']],
    ['LAX', '로스앤젤레스', ['LA', '엘에이', 'losangeles']],
    ['SFO', '샌프란시스코', ['sanfrancisco']],
    ['LAS', '라스베가스', ['lasvegas']],
    ['HNL', '호놀룰루', ['하와이', 'honolulu', 'hawaii']],
    ['SEA', '시애틀', ['seattle']],
    ['ORD', '시카고', ['chicago']],
    ['BOS', '보스턴', ['boston']],
    ['MIA', '마이애미', ['miami']],
    ['WAS', '워싱턴', ['washington', 'IAD']],
    ['ATL', '애틀랜타', ['atlanta']],
    ['DFW', '댈러스', ['dallas']],
    ['YYZ', '토론토', ['toronto', '캐나다']],
    ['YVR', '밴쿠버', ['vancouver']],
    ['CUN', '칸쿤', ['cancun', '멕시코']],
    ['MEX', '멕시코시티', ['mexicocity']],
  ]],
  ['유럽', [
    ['LON', '런던', ['london', '영국', 'LHR']],
    ['PAR', '파리', ['paris', '프랑스', 'CDG']],
    ['ROM', '로마', ['rome', '이탈리아', 'FCO']],
    ['MIL', '밀라노', ['milan']],
    ['VCE', '베네치아', ['베니스', 'venice']],
    ['BCN', '바르셀로나', ['barcelona', '스페인']],
    ['MAD', '마드리드', ['madrid']],
    ['FRA', '프랑크푸르트', ['frankfurt', '독일']],
    ['MUC', '뮌헨', ['munich']],
    ['AMS', '암스테르담', ['amsterdam', '네덜란드']],
    ['ZRH', '취리히', ['zurich', '스위스']],
    ['VIE', '비엔나', ['빈', 'vienna', '오스트리아']],
    ['PRG', '프라하', ['prague', '체코']],
    ['BUD', '부다페스트', ['budapest', '헝가리']],
    ['IST', '이스탄불', ['istanbul', '터키', '튀르키예']],
    ['HEL', '헬싱키', ['helsinki', '핀란드']],
    ['CPH', '코펜하겐', ['copenhagen']],
    ['ARN', '스톡홀름', ['stockholm']],
    ['LIS', '리스본', ['lisbon', '포르투갈']],
    ['ATH', '아테네', ['athens', '그리스']],
    ['DBV', '두브로브니크', ['dubrovnik', '크로아티아']],
  ]],
  ['오세아니아', [
    ['SYD', '시드니', ['sydney', '호주']],
    ['MEL', '멜버른', ['melbourne']],
    ['BNE', '브리즈번', ['brisbane']],
    ['OOL', '골드코스트', ['goldcoast']],
    ['CNS', '케언즈', ['cairns']],
    ['AKL', '오클랜드', ['auckland', '뉴질랜드']],
    ['NAN', '나디', ['nadi', '피지']],
  ]],
  ['중동 · 인도', [
    ['DXB', '두바이', ['dubai']],
    ['AUH', '아부다비', ['abudhabi']],
    ['DOH', '도하', ['doha', '카타르']],
    ['TLV', '텔아비브', ['telaviv', '이스라엘']],
    ['CAI', '카이로', ['cairo', '이집트']],
    ['DEL', '델리', ['delhi', '인도']],
    ['BOM', '뭄바이', ['mumbai']],
    ['KTM', '카트만두', ['kathmandu', '네팔']],
    ['CMB', '콜롬보', ['colombo', '스리랑카']],
    ['MLE', '몰디브', ['male', 'maldives']],
  ]],
]

// 코드 → 한국어 이름 (전체)
export const AIRPORT_NAME = Object.fromEntries(
  AIRPORT_REGIONS.flatMap(([, items]) => items.map(([code, name]) => [code, name]))
)
// 검색 오버레이용 그룹 (label=한국어명, sub=IATA, kw=별칭+코드로 영문·이표기 검색)
export const AIRPORT_GROUPS = AIRPORT_REGIONS.map(([title, items]) => ({
  title,
  items: items.map(([code, name, aliases = []]) => ({
    id: code, label: name, sub: code, icon: '🏙️', kw: [code, ...aliases],
  })),
}))
