// 목적지 지식 DB — '어디 갈까?' 추천의 두뇌 (LLM 없이 칩 매칭으로 동작). 사람이 큐레이션.
// codes: 이 목적지에 해당하는 IATA(복수 공항). themes/goodFor/badFor/months/budgetMin/caution.
export const DESTINATIONS = [
  { codes: ['FUK'], name: '후쿠오카', country: '일본', region: '아시아', flightMin: 80, budgetMin: 300000, budget: '30만~45만',
    themes: ['맛집', '쇼핑', '온천'], goodFor: ['혼자', '커플', '친구', '부모님'], badFor: ['휴양'], months: [3,4,5,9,10,11,1,2], caution: ['주말 출발은 가격이 빨리 올라요'] },
  { codes: ['KIX'], name: '오사카', country: '일본', region: '아시아', flightMin: 110, budgetMin: 300000, budget: '30만~50만',
    themes: ['맛집', '쇼핑', '도시'], goodFor: ['혼자', '커플', '친구', '가족', '부모님'], badFor: ['휴양'], months: [3,4,5,9,10,11], caution: ['벚꽃·단풍철은 비싸요'] },
  { codes: ['TYO', 'HND', 'NRT'], name: '도쿄', country: '일본', region: '아시아', flightMin: 140, budgetMin: 350000, budget: '35만~55만',
    themes: ['쇼핑', '맛집', '도시'], goodFor: ['혼자', '커플', '친구'], badFor: ['휴양'], months: [3,4,5,9,10,11], caution: ['도심 호텔이 비싼 편'] },
  { codes: ['CTS'], name: '삿포로', country: '일본', region: '아시아', flightMin: 170, budgetMin: 400000, budget: '40만~60만',
    themes: ['자연', '맛집', '온천'], goodFor: ['커플', '가족', '부모님'], badFor: [], months: [1,2,6,7,12], caution: ['겨울은 인기라 빨리 매진'] },
  { codes: ['OKA'], name: '오키나와', country: '일본', region: '아시아', flightMin: 150, budgetMin: 400000, budget: '40만~60만',
    themes: ['휴양', '자연', '바다'], goodFor: ['커플', '가족', '친구'], badFor: ['쇼핑'], months: [4,5,9,10], caution: ['장마(6월)·태풍철 주의'] },
  { codes: ['TPE'], name: '타이베이', country: '대만', region: '아시아', flightMin: 150, budgetMin: 300000, budget: '30만~45만',
    themes: ['맛집', '쇼핑', '도시', '온천'], goodFor: ['혼자', '커플', '친구', '부모님'], badFor: ['휴양'], months: [3,4,10,11,12], caution: ['여름은 덥고 습해요'] },
  { codes: ['KHH'], name: '가오슝', country: '대만', region: '아시아', flightMin: 170, budgetMin: 300000, budget: '30만~45만',
    themes: ['맛집', '자연', '도시'], goodFor: ['커플', '친구', '부모님'], badFor: [], months: [3,4,11,12], caution: [] },
  { codes: ['HKG'], name: '홍콩', country: '홍콩', region: '아시아', flightMin: 210, budgetMin: 350000, budget: '35만~55만',
    themes: ['쇼핑', '맛집', '도시'], goodFor: ['커플', '친구'], badFor: ['휴양', '부모님'], months: [3,4,10,11,12], caution: ['여름 무더위·습도'] },
  { codes: ['DAD'], name: '다낭', country: '베트남', region: '동남아', flightMin: 290, budgetMin: 350000, budget: '35만~50만',
    themes: ['휴양', '바다', '맛집'], goodFor: ['커플', '가족', '친구', '부모님'], badFor: [], months: [2,3,4,5,6,7,8], caution: ['우기(10~12월) 비 많음'] },
  { codes: ['NHA'], name: '나트랑', country: '베트남', region: '동남아', flightMin: 320, budgetMin: 350000, budget: '35만~50만',
    themes: ['휴양', '바다'], goodFor: ['커플', '가족', '친구'], badFor: ['쇼핑'], months: [1,2,3,4,6,7,8], caution: ['우기 주의'] },
  { codes: ['HAN'], name: '하노이', country: '베트남', region: '동남아', flightMin: 290, budgetMin: 350000, budget: '35만~50만',
    themes: ['맛집', '도시'], goodFor: ['친구', '부모님', '혼자'], badFor: ['휴양'], months: [3,4,10,11], caution: ['여름 무더위'] },
  { codes: ['SGN'], name: '호치민', country: '베트남', region: '동남아', flightMin: 330, budgetMin: 350000, budget: '35만~50만',
    themes: ['맛집', '도시'], goodFor: ['친구', '커플', '혼자'], badFor: ['휴양'], months: [12,1,2,3], caution: ['우기(5~10월)'] },
  { codes: ['BKK'], name: '방콕', country: '태국', region: '동남아', flightMin: 350, budgetMin: 350000, budget: '35만~55만',
    themes: ['맛집', '쇼핑', '도시'], goodFor: ['혼자', '커플', '친구'], badFor: ['부모님'], months: [11,12,1,2], caution: ['4월 무더위'] },
  { codes: ['HKT'], name: '푸켓', country: '태국', region: '동남아', flightMin: 380, budgetMin: 450000, budget: '45만~65만',
    themes: ['휴양', '바다'], goodFor: ['커플', '가족', '친구'], badFor: ['쇼핑'], months: [11,12,1,2,3], caution: ['우기(5~10월)'] },
  { codes: ['CEB'], name: '세부', country: '필리핀', region: '동남아', flightMin: 280, budgetMin: 350000, budget: '35만~55만',
    themes: ['휴양', '바다'], goodFor: ['커플', '가족', '친구'], badFor: ['쇼핑'], months: [1,2,3,4,5], caution: ['우기·태풍 주의'] },
  { codes: ['MNL'], name: '마닐라', country: '필리핀', region: '동남아', flightMin: 230, budgetMin: 300000, budget: '30만~45만',
    themes: ['도시'], goodFor: ['친구', '혼자'], badFor: ['부모님', '휴양'], months: [12,1,2,3,4], caution: ['교통 혼잡'] },
  { codes: ['BKI'], name: '코타키나발루', country: '말레이시아', region: '동남아', flightMin: 320, budgetMin: 400000, budget: '40만~60만',
    themes: ['휴양', '바다', '자연'], goodFor: ['커플', '가족'], badFor: ['쇼핑'], months: [3,4,5,6,7,8,9], caution: ['우기(11~2월)'] },
  { codes: ['GUM'], name: '괌', country: '괌', region: '괌·사이판', flightMin: 240, budgetMin: 450000, budget: '45만~70만',
    themes: ['휴양', '바다', '쇼핑'], goodFor: ['커플', '가족', '친구'], badFor: [], months: [1,2,3,4,11,12], caution: ['성수기(방학) 가격 급등'] },
]
